### ISSUE TITLE
clusterfeaturelayer dissolving clusters results in popup

### ISSUE THREAD

**Issue by kbor-maschmi** [conterra/mapapps-clusterfeaturelayer#10]
Clicking on a cluster to dissolve it and zoom into the map queries underlying features (such as an area-layer) and results in opening a popup-window when queryable features are hit.

**Comment by matthiasstein** [comment]
It is impossible to prevent pop-ups of other layers when clicking on a cluster. Therefore, new properties have been added in version https://github.com/conterra/mapapps-clusterfeaturelayer/releases/tag/3.3.0:
- zoomOnClusterClick: enable or disable the zoom on a cluster click
- showClusterPopup: show a specific cluster popop
