### ISSUE TITLE
Clusterinfo popup doesn't contain info in map.apps 4.12.0

### ISSUE THREAD

**Issue by sholtkamp** [conterra/mapapps-clusterfeaturelayer#11]
The info popup summarizing a cluster merely contains a "," as of now. 

Reproduction:
- Open either sample app 1 or local clusterfeaturelayer project
- Click on cluster

This issue also persists in the map.apps 4.13.0-SNAPSHOT version

**Comment by matthiasstein** [comment]
This is a missing feature. It was added in: https://github.com/conterra/mapapps-clusterfeaturelayer/commit/c79d679c187eb6c8cef8a5aa4e78feae996c94df
