### ISSUE TITLE
Startfehler in map.apps 4.11.1 und Firefox

### ISSUE THREAD

**Issue by gedicb** [conterra/mapapps-clusterfeaturelayer#12]
Die Version 3.3.1 verursacht in unseren Themenkarten einen Fehler. Der Start der Themenkarte bricht ab.

Wir setzen folgende Versionen ein:
map.apps: 4,11,1
firefox: 91.5.0esr

In der Konsole wird folgender Fehler gelistet:
https://...../mapapps/resources/jsregistry/root/esri/4.18.1/rest/support/Query.js -> Fehler: 404 Not Found

**Comment by matthiasstein** [comment]
Die Version 3.3.1 benötigt map.apps 4.12, da neue Esri-Klassen verwendet werden, die es in 4.11 noch nicht gibt. Nutzen Sie bitte weiterhin Version 3.3.0.
